version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Generate Keys
          command: ./.keys/generate-keys.sh
      - run:
          name: Build script
          command: ./build.sh
